# Generated by Django 6.0.2 on 2026-02-22 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dim_score',
            field=models.IntegerField(blank=True, help_text='DİM score between 0 and 700', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(700)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='IELTS score between 0.0 and 9.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sat_score',
            field=models.IntegerField(blank=True, help_text='SAT score between 400 and 1600', null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(1600)]),
        ),
    ]
