# Generated by Django 6.0.2 on 2026-02-28 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_dim_score_userprofile_ielts_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='toefl_score',
            field=models.IntegerField(blank=True, help_text='TOEFL score between 0 and 120', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
