# Generated by Django 6.0.2 on 2026-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_toefl_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject_group',
            field=models.CharField(blank=True, choices=[('I', 'I Group'), ('II', 'II Group'), ('III', 'III Group'), ('IV', 'IV Group'), ('V', 'V Group')], max_length=5, null=True),
        ),
    ]
