# Generated by Django 6.0.2 on 2026-02-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='dormitory_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum IELTS score e.g. 6.5', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_score',
            field=models.IntegerField(blank=True, help_text='Minimum SAT score e.g. 1200', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarships',
            field=models.TextField(blank=True, help_text='Enter scholarships separated by commas e.g. "Merit Scholarship, Need-Based Grant"'),
        ),
    ]
