# Generated by Django 6.0.2 on 2026-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_dormitory_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='qs_ranking',
            field=models.IntegerField(blank=True, help_text='QS World University Ranking number (lower is better)', null=True),
        ),
    ]
