# Generated by Django 6.0.2 on 2026-02-22 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_qs_ranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('title', models.CharField(max_length=150)),
                ('experience', models.TextField(help_text='Describe your overall experience')),
                ('pros', models.TextField(help_text='List the key advantages')),
                ('cons', models.TextField(help_text='List the key disadvantages')),
                ('tips', models.TextField(blank=True, help_text='Advice for future applicants')),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('is_verified', models.BooleanField(default=False, help_text="Mark as Verified Participant if the user's participation is confirmed")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('university', 'user')},
            },
        ),
    ]
