# Generated by Django 6.0.2 on 2026-02-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='state_order_places',
            field=models.PositiveIntegerField(blank=True, help_text='Number of state-funded (grant) places available (0 = none)', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='tuition_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual tuition for fee-paying students (AZN or USD)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='1 = top choice')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_entries', to='universities.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rank Entries',
                'ordering': ['position'],
                'unique_together': {('user', 'faculty')},
            },
        ),
    ]
