# Generated by Django 6.0.2 on 2026-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_faculty_state_order_places_faculty_tuition_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application Deadline', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 4 years, 5 years', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='language',
            field=models.CharField(blank=True, help_text='e.g. English, Azerbaijani', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_year_score',
            field=models.IntegerField(blank=True, help_text="Last year's minimum passing score (e.g. 680)", null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject_group',
            field=models.CharField(blank=True, choices=[('I', 'I Group'), ('II', 'II Group'), ('III', 'III Group'), ('IV', 'IV Group'), ('V', 'V Group')], max_length=5, null=True),
        ),
    ]
