# Generated by Django 6.0.2 on 2026-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_faculty_deadline_faculty_duration_faculty_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='last_year_score_paid',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Paid minimum score (e.g. 623.2)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='last_year_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='State order minimum score (e.g. 672.8)', max_digits=5, null=True),
        ),
    ]
