# Generated by Django 6.0.2 on 2026-03-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_faculty_last_year_score_paid_and_more'),
    ]

    operations = [
    ]
